### PR TITLE
Added disallow-cluster-admin for OPA

### PR DESCRIPTION
**Pull request by michaelkotelnikov**
Solves https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/108.

### CODE REVIEW

**Comment by michaelkotelnikov** [comment]
@igorkchyts and @cloudlabmaz Currently, the policy is very basic, and has some 'insecure" definitions in the constraint.yaml file (e.g - the `default` account can be correlated with the `cluster-admin` ClusterRole).

For now, I think that it provides some added value to customers that want to consume the policy. If you have some ideas about how to enhance the policy, feel free to commit to my fork.

**Comment by igorkchyts** [comment]
> @igorkchyts and @cloudlabmaz Currently, the policy is very basic, and has some 'insecure" definitions in the constraint.yaml file (e.g - the `default` account can be correlated with the `cluster-admin` ClusterRole).
> 
> For now, I think that it provides some added value to customers that want to consume the policy. If you have some ideas about how to enhance the policy, feel free to commit to my fork.

@michaelkotelnikov  
The problem with listing user,groups and serviceaccounts under the same constraint.parameter is that 'ServiceAccounts' are namespace scoped. 
To solve this I suggest to develop the policy structured with 3 conditions(Violations): 
1. For Allowed users 
2. For Allowed Groups
3. For Allowed ServiceAccounts - In this condition both the name and the namespace will be checked against the constraint.parameter. For example ServiceAccount 'default' from namespace 'default' is allowed as opposed to ServiceAccount 'default' from namespace 'web-dev' which is not allowed

**Comment by michaelkotelnikov** [comment]
@igorkchyts Let's make it happen. Involving @tommeramber to contribute to this issue.

**Comment by michaelkotelnikov** [comment]
@igorkchyts @tommeramber Added a fix. Seems to work now.

**Review by tommeramber — APPROVED** [review]

**Review by tommeramber — APPROVED** [review]
I'll add the README + tests in a following PR

**Pull request merged**
