### PR TITLE
Added the "Disallow self provisioner ClusterRole"  gatekeeper policy

### PR DESCRIPTION
**Pull request by michaelkotelnikov**
Gatekeeper monitors the self-provisioners ClusterRoleBinding, and does not allow any subjects to be attached to it.

### CODE REVIEW

**Review by igorkchyts — COMMENTED** [review]
Still allow users to be added with clusterrole self-provisioner as new clusterrolebinding is created with new name

**Review by igorkchyts — COMMENTED** [review]
@michaelkotelnikov 
Violation is not working on 4.6 cluster. 
No violation showed while clusterrolebinding 'self-provisioner' exists

**Comment by michaelkotelnikov** [comment]
Fixed. The policy now disallows adding users as self-provisioners by running `oc adm policy add-cluster-role-to-user self-provisioner <user>`

**Review by igorkchyts — APPROVED** [review]
Tested on 4.6 OCP. Thanks.

**Pull request merged**
